-- MySQL Script generated by MySQL Workbench
-- Wed Jan 25 17:23:22 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema ristorante_progetto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema ristorante_progetto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ristorante_progetto` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `ristorante_progetto`.`ristorante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ristorante_progetto`.`ristorante` (
  `id_ristorante` INT NULL,
  `nome_ristorante` VARCHAR(64) NOT NULL,
  `indirizzo` VARCHAR(64) NOT NULL,
  `tipi_di_menu` ENUM('carne', 'pesce', 'vegano', 'misto') NOT NULL,
  `capienza_massima_tavoli` INT NOT NULL,
  PRIMARY KEY (`id_ristorante`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ristorante_progetto`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ristorante_progetto`.`cliente` (
  `id_cliente` INT AUTO_INCREMENT,
  `nome_cliente` VARCHAR(64) NOT NULL,
  `cognome_cliente` VARCHAR(64) NOT NULL,
  `email` VARCHAR(64) NOT NULL,
  `preferred_menu` ENUM('CARNE', 'PESCE', 'VEGANO', 'MISTO') NOT NULL,
  `tavolo_numero_tavolo` INT,
  PRIMARY KEY (`id_cliente`),
  INDEX `fk_cliente_tavolo1_idx` (`tavolo_numero_tavolo` ASC) VISIBLE,
  CONSTRAINT `fk_cliente_tavolo1`
    FOREIGN KEY (`tavolo_numero_tavolo`)
    REFERENCES `ristorante_progetto`.`tavolo` (`numero_tavolo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;
-- -----------------------------------------------------
-- Table `ristorante_progetto`.`portata`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ristorante_progetto`.`portata` (
  `id_portata` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(64) NOT NULL,
  `prezzo` DECIMAL NOT NULL,
  `ingredienti` VARCHAR(64) NOT NULL,
  `tipo_portata` ENUM('Carne', 'Pesce', 'Vegano', 'Misto') NOT NULL,
  PRIMARY KEY (`id_portata`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ristorante_progetto`.`bevanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ristorante_progetto`.`bevanda` (
  `id_bevanda` INT NOT NULL AUTO_INCREMENT,
  `nome_bevanda` VARCHAR(64) NOT NULL,
  `prezzo_bevanda` DECIMAL NOT NULL,
  `ingredienti` VARCHAR(45) NOT NULL,
  `tipo_bevanda_menu` ENUM('CARNE', 'PESCE', 'VEGANO', 'MISTO') NOT NULL,
  `tipo_bevanda` ENUM('COLA', 'LIQUORE', 'ACQUA', 'BIRRA') NOT NULL,
  `portata_id_portata` INT,
  PRIMARY KEY (`id_bevanda`),
  INDEX `fk_bevanda_portata1_idx` (`portata_id_portata` ASC) VISIBLE,
  CONSTRAINT `fk_bevanda_portata1`
    FOREIGN KEY (`portata_id_portata`)
    REFERENCES `ristorante_progetto`.`portata` (`id_portata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ristorante_progetto`.`primo_piatto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ristorante_progetto`.`primo_piatto` (
  `id_primo_piatto` INT NOT NULL AUTO_INCREMENT,
  `nome_primo_piatto` VARCHAR(64) NOT NULL,
  `prezzo_primo_piatto` DECIMAL NOT NULL,
  `ingredienti_primo_piatto` VARCHAR(64) NOT NULL,
  `tipo_primo_piatto` ENUM('Carne', 'Pesce', 'Vegano', 'Misto') NOT NULL,
  `portata_id_portata` INT,
  PRIMARY KEY (`id_primo_piatto`),
  INDEX `fk_primo_piatto_portata1_idx` (`portata_id_portata` ASC) VISIBLE,
    CONSTRAINT `fk_primo_piatto_portata1`
      FOREIGN KEY (`portata_id_portata`)
      REFERENCES `ristorante_progetto`.`portata` (`id_portata`)
      ON DELETE NO ACTION
      ON UPDATE NO ACTION)
  ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ristorante_progetto`.`secondo_piatto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ristorante_progetto`.`secondo_piatto` (
  `id_secondo_piatto` INT NOT NULL AUTO_INCREMENT,
  `nome_secondo_piatto` VARCHAR(64) NOT NULL,
  `prezzo_secondo_piatto` DECIMAL NOT NULL,
  `ingredienti_secondo_piatto` VARCHAR(64) NOT NULL,
  `tipo_secondo_piatto` ENUM('carne', 'pesce', 'vegano', 'misto') NOT NULL,
  `contorno` VARCHAR(64) NOT NULL,
  `cottura` ENUM('al_sangue', 'media', 'ben_cotta') NOT NULL,
  `portata_id_portata` INT,
  PRIMARY KEY (`id_secondo_piatto`),
  INDEX `fk_secondo_piatto_portata1_idx` (`portata_id_portata` ASC) VISIBLE,
  CONSTRAINT `fk_secondo_piatto_portata1`
    FOREIGN KEY (`portata_id_portata`)
    REFERENCES `ristorante_progetto`.`portata` (`id_portata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ristorante_progetto`.`dolce`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ristorante_progetto`.`dolce` (
  `id_dolce` INT NOT NULL AUTO_INCREMENT,
  `nome_dolce` VARCHAR(64) NOT NULL,
  `prezzo_dolce` DECIMAL NOT NULL,
  `ingredienti` VARCHAR(64) NOT NULL,
  `tipo_dolce` ENUM('CARNE', 'PESCE', 'VEGANO', 'MISTO') NOT NULL,
  `portata_id_portata` INT,
  PRIMARY KEY (`id_dolce`),
  INDEX `fk_dolce_portata1_idx` (`portata_id_portata` ASC) VISIBLE,
  CONSTRAINT `fk_dolce_portata1`
    FOREIGN KEY (`portata_id_portata`)
    REFERENCES `ristorante_progetto`.`portata` (`id_portata`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ristorante_progetto`.`tavolo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ristorante_progetto`.`tavolo` (
  `id_tavolo` INT NOT NULL AUTO_INCREMENT,
  `numero_tavolo` INT NOT NULL,
  `posizione_tavolo` ENUM('Esterno_Terrazzo', 'Esterno_Vista_Mare', 'Esterno_Giardino', 'Interno') NOT NULL,
  `ristorante_id_ristorante` INT,
  PRIMARY KEY (`numero_tavolo`),
  INDEX `fk_tavolo_ristorante1_idx` (`ristorante_id_ristorante` ASC) VISIBLE,
  CONSTRAINT `fk_tavolo_ristorante1`
    FOREIGN KEY (`ristorante_id_ristorante`)
    REFERENCES `ristorante_progetto`.`ristorante` (`id_ristorante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `ristorante_progetto`.`prenotazione`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`prenotazione` (
  `id_prenotazione` INT NOT NULL AUTO_INCREMENT,
  `nominativo` VARCHAR(64) NOT NULL,
  `contactinfo` VARCHAR(64) NOT NULL,
  `data_prenotazione` DATE NOT NULL,
  `ristorante_id_ristorante` INT,
  `cliente_id_cliente` INT,
  PRIMARY KEY (`id_prenotazione`),
  INDEX `fk_prenotazione_ristorante1_idx` (`ristorante_id_ristorante` ASC) VISIBLE,
  INDEX `fk_prenotazione_cliente1_idx` (`cliente_id_cliente` ASC) VISIBLE,
  CONSTRAINT `fk_prenotazione_ristorante1`
    FOREIGN KEY (`ristorante_id_ristorante`)
    REFERENCES `ristorante_progetto`.`ristorante` (`id_ristorante`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_prenotazione_cliente1`
    FOREIGN KEY (`cliente_id_cliente`)
    REFERENCES `mydb`.`cliente` (`id_cliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;